name: json_object_convert_help
description: XXXXXXXXXXXXXX
version: 0.0.1
author: fdsaf
homepage: https://baidu.com
documentation:

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  jaguar_query: ^2.2.4
  quiver: ^2.0.0
  path: ^1.6.0
  meta: ^1.1.6

dev_dependencies:
  test: ^1.2.0
  jaguar_query_postgres: # ^0.2.5
    path: ../postgres
  build_runner: ^0.10.0
  jaguar_orm_gen:
    path: ../generator