# Read about `build.yaml` at https://pub.dartlang.org/packages/build_config
builders:
  json_object_convert:
    import: "package:json_object_convert/builder.dart"
    builder_factories: ["entryPoint", "entryPoint2"]
    build_extensions: {".dart": [".test.dart"]}
    auto_apply: root_package
    build_to: source