name: json_object_convert
description: Generator for jsonObject
version: 0.0.2
author: aliya
homepage: https://baidu.com

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  jaguar_query: ^2.2.4
  jaguar_orm: ^2.2.5
  analyzer: ^0.32.0
  build: ^0.12.0
  logging: ^0.11.0
  source_gen: ^0.9.0
  meta: ^1.1.5
  json_object_convert_help:
    path: ../../librarys/json_object_convert_help

dev_dependencies:
  test: ^1.3.0
  build_runner: ^0.10.0
  build_test: ^0.10.3
  collection: ^1.14.10
  path: ^1.6.2



